language: node_js
node_js: "12"
cache: npm
dist: bionic

addons:
  chrome: "stable"
  firefox: "latest"

notifications:
  email:
    - leticiacf.fernandes@gmail.com

before_script: 
  - "npm run lint"
  - "npm run test"

after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"